#version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"  # برای ارتباط Agentها
      # - "9000:9000"   # پورت HTTP
      - "9443:9443"   # پورت HTTPS
    restart: always
    depends_on:
      - dns-srv
      - ntp-srv
      - influx-db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    environment:
      - TZ=${TZ}
      - PORTAINER_HTTP_PORT=9000
      - PORTAINER_HTTPS_PORT=9443
      - PORTAINER_ADMIN_PASSWORD=${PORTAINER_ADMIN_PASSWORD}
      - PORTAINER_EDGE=0
      - LOG_LEVEL=${LOG_LEVEL}
    networks:
      - internal_net

volumes:
  portainer:
    external: true

networks:
  internal_net:
    external: true
