#version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      # - "8000:8000"  # برای ارتباط Agentها
      # - "9000:9000"   # پورت HTTP
      - "9443:9443"   # پورت HTTPS
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      PORTAINER_HTTPS_PORT: "${PORTAINER_HTTPS_PORT}"
      PORTAINER_ADMIN_PASSWORD: "${PORTAINER_ADMIN_PASSWORD}"
      PORTAINER_EDGE: 0
      LOG_LEVEL: "${LOG_LEVEL}"
    networks:
      - internal_net

  influx-db:
    image: influxdb:3.4.1-core
    container_name: influx-db
    restart: always
    ports:
      # - "8086:8086"  # پورت HTTP برای ارتباط با کلاینت‌ها
      - "8181:8181"  # پورت API داخلی (برای ارتباط بین نودها)
    depends_on:
      - dns-srv
      - ntp-srv
    command: >
      serve 
      --node-id influxdb-01 
      --object-store file 
      --data-dir /var/lib/influxdb3
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - TZ=${TZ}
      - INFLUXD_LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - influx-db:/var/lib/influxdb3
    networks:
      - internal_net
      - db_net

volumes:
  portainer:
    external: true
  influx-db:
    external: true

networks:
  internal_net:
    external: true
  db_net:
    external: true
